application: xeuropool
version: 2
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: view/img/favicon.ico
  upload: view/img/favicon.ico

- url: /style
  static_dir: view/style

- url: /img
  static_dir: view/img

- url: /stats.*
  script: $PYTHON_LIB/google/appengine/ext/appstats/ui.py

- url: /doc
  static_dir: doc

- url: .*
  script: main.py
