environment           = "prod"
domain_name           = "pool.xczimi.com"
route53_zone_name     = "xczimi.com"
current_tournament_id = "fwc26"
auth0_domain          = "xpool.ca.auth0.com"
result_user_email     = "pool@xczimi.com"
