[package]
name = "xtask"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "xtask"
path = "src/main.rs"

[dependencies]
domain.workspace = true
fwc26.workspace = true
storage.workspace = true
anyhow.workspace = true
tokio.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
clap = { version = "4", features = ["derive"] }
dotenvy = "0.15"
rand = "0.8"

[lib]
name = "xtask"
path = "src/lib.rs"

[dev-dependencies]
